import { env } from "./index.js";

interface Config {
  NODE_ENV: string;
  DATABASE_URL: string;
  CORS_ORIGIN?: string;
  CMS_URL?: string;
  REDIS_URL: string;
  PORT: number;
  SERVER_SECRET: string;
  GHOST_PORTFOLIO_CMS_REFRESH_TOKEN_EXPIRES:string;
  GHOST_PORTFOLIO_CMS_ACCESS_TOKEN_EXPIRES:string;
  JWT_SECRET:string;
  PORTFOLIO_CMS_SESSION_NAME: string;
  GHOST_PORTFOLIO_CMS_ACCESS_TOKEN_NAME: string;
  GHOST_PORTFOLIO_CMS_REFRESH_TOKEN_NAME: string;
  CLOUD_NAME: string;
  CLOUDINARY_API_KEY: string;
  CLOUDINARY_SECRET_KEY: string;
}

const config: Config = {
  NODE_ENV: env.NODE_ENV || "development",
  DATABASE_URL: env.DATABASE_URL || "",
  CORS_ORIGIN: env.CORS_ORIGIN,
  CMS_URL: env.CMS_URL,
  REDIS_URL: env.REDIS_URL || "",
  PORT: env.PORT ,
  SERVER_SECRET: env.SERVER_SECRET || "",
  GHOST_PORTFOLIO_CMS_ACCESS_TOKEN_EXPIRES: env.GHOST_PORTFOLIO_CMS_ACCESS_TOKEN_EXPIRES,
  GHOST_PORTFOLIO_CMS_REFRESH_TOKEN_EXPIRES: env.GHOST_PORTFOLIO_CMS_REFRESH_TOKEN_EXPIRES,
  JWT_SECRET: env.JWT_SECRET || "",
  PORTFOLIO_CMS_SESSION_NAME: env.PORTFOLIO_CMS_SESSION_NAME,
  GHOST_PORTFOLIO_CMS_ACCESS_TOKEN_NAME: env.GHOST_PORTFOLIO_CMS_ACCESS_TOKEN_NAME,
  GHOST_PORTFOLIO_CMS_REFRESH_TOKEN_NAME: env.GHOST_PORTFOLIO_CMS_REFRESH_TOKEN_NAME,
  CLOUD_NAME: env.CLOUD_NAME,
  CLOUDINARY_API_KEY: env.CLOUDINARY_API_KEY,
  CLOUDINARY_SECRET_KEY: env.CLOUDINARY_SECRET_KEY
};

export default config;
